apiVersion: influxdata.com/v2alpha1
kind: Task
metadata:
    name: fetch-usgs-earthquake-task
spec:
    every: 5m
    name: Fetch USGS Earthquake Data
    query: |-
        import "experimental/csv"

        csv.from(url: "https://influx-testdata.s3.amazonaws.com/usgs-earthquake-all-week-annotated.csv")
        |> to(bucket: "sample_data")
    status: active
