apiVersion: influxdata.com/v2alpha1
kind: Label
metadata:
    name: vigorous-pike-607001
spec:
    color: '#326BBA'
    name: covid
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
    name: dangerous-cori-607005
spec:
    associations:
      - kind: Label
        name: vigorous-pike-607001
    name: covid
---
apiVersion: influxdata.com/v2alpha1
kind: Dashboard
metadata:
    name: zealous-benz-e07001
spec:
    associations:
      - kind: Label
        name: vigorous-pike-607001
    charts:
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Argentina
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "exec_argentina")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
        width: 2
      - colors:
          - hex: '#ffffff'
            name: white
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Nuevos casos 24 horas
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -24h)
                  |> filter(fn: (r) => r["_measurement"] == "exec_argentina")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
                  |> increase()
                  |> yield(name: "increase")
        width: 2
        yPos: 1
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 2
        kind: Single_Stat
        name: Total Casos
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -12h)
                  |> filter(fn: (r) => r["_measurement"] == "exec_brasil" or r["_measurement"] == "exec_chile" or r["_measurement"] == "exec_paraguay" or r["_measurement"] == "exec_argentina" or r["_measurement"] == "exec_bolivia" or r["_measurement"] == "exec_uruguay")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
                  |> mean()
                  |> group()
                  |> sum()
        width: 2
        yPos: 2
      - colors:
          - hex: '#DC4E58'
            name: fire
            type: text
        decimalPlaces: 2
        height: 2
        kind: Single_Stat
        name: Fallecidos
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -12h)
                  |> filter(fn: (r) => r["_measurement"] == "exec_argentina" or r["_measurement"] == "exec_uruguay" or r["_measurement"] == "exec_bolivia" or r["_measurement"] == "exec_paraguay" or r["_measurement"] == "exec_chile" or r["_measurement"] == "exec_brasil")
                  |> filter(fn: (r) => r["_field"] == "location_latest_deaths")
                  |> mean()
                  |> group()
                  |> sum()
        width: 2
        yPos: 4
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 2
        kind: Single_Stat
        name: Casos - Total
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "exec_worldwide")
                  |> filter(fn: (r) => r["_field"] == "latest_confirmed")
        width: 2
        yPos: 6
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 2
        kind: Single_Stat
        name: Fallecidos - Todo el mundo
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "exec_worldwide")
                  |> filter(fn: (r) => r["_field"] == "latest_deaths")
        width: 2
        yPos: 8
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Bolivia
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "exec_bolivia")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
        width: 2
        xPos: 2
      - colors:
          - hex: '#ffffff'
            name: white
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Nuevos casos 24 horas
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -24h)
                  |> filter(fn: (r) => r["_measurement"] == "exec_bolivia")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
                  |> increase()
                  |> yield(name: "increase")
        width: 2
        xPos: 2
        yPos: 1
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            label: Cantidad de Casos
            name: y
            scale: linear
        colors:
          - hex: '#31C0F6'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#A500A5'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#FF7E27'
            name: Nineteen Eighty Four
            type: scale
        geom: line
        height: 2
        kind: Xy
        name: Total Casos (Visualización 7 días)
        position: overlaid
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -7d)
                  |> filter(fn: (r) => r["_measurement"] == "exec_argentina" or r["_measurement"] == "exec_uruguay" or r["_measurement"] == "exec_bolivia" or r["_measurement"] == "exec_paraguay" or r["_measurement"] == "exec_chile" or r["_measurement"] == "exec_brasil")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
        width: 10
        xCol: _time
        xPos: 2
        yCol: _value
        yPos: 2
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            label: Cantidad de Casos
            name: y
            scale: linear
        colors:
          - hex: '#31C0F6'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#A500A5'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#FF7E27'
            name: Nineteen Eighty Four
            type: scale
        geom: line
        height: 2
        kind: Xy
        name: Fallecidos por Pais
        position: overlaid
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -7d)
                  |> filter(fn: (r) => r["_measurement"] == "exec_argentina" or r["_measurement"] == "exec_uruguay" or r["_measurement"] == "exec_bolivia" or r["_measurement"] == "exec_paraguay" or r["_measurement"] == "exec_chile" or r["_measurement"] == "exec_brasil")
                  |> filter(fn: (r) => r["_field"] == "location_latest_deaths")
        width: 10
        xCol: _time
        xPos: 2
        yCol: _value
        yPos: 4
      - axes:
          - base: "10"
            name: x
            scale: linear
          - base: "10"
            label: Cantidad de Casos
            name: y
            scale: linear
        colors:
          - hex: '#31C0F6'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#A500A5'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#FF7E27'
            name: Nineteen Eighty Four
            type: scale
        geom: line
        height: 2
        kind: Xy
        name: Casos Mundial - Grafico
        position: overlaid
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -7d)
                  |> filter(fn: (r) => r["_measurement"] == "exec_worldwide")
                  |> filter(fn: (r) => r["_field"] == "latest_confirmed")
        width: 10
        xCol: _time
        xPos: 2
        yCol: _value
        yPos: 6
      - axes:
          - base: "10"
            name: y
            scale: linear
          - base: "10"
            name: x
            scale: linear
        colors:
          - hex: '#31C0F6'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#A500A5'
            name: Nineteen Eighty Four
            type: scale
          - hex: '#FF7E27'
            name: Nineteen Eighty Four
            type: scale
        geom: line
        height: 2
        kind: Xy
        name: Fallecidos - Mundo
        position: overlaid
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -7d)
                  |> filter(fn: (r) => r["_measurement"] == "exec_worldwide")
                  |> filter(fn: (r) => r["_field"] == "latest_deaths")
        width: 10
        xCol: _time
        xPos: 2
        yCol: _value
        yPos: 8
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Brasil
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "exec_brasil")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
        width: 2
        xPos: 4
      - colors:
          - hex: '#ffffff'
            name: white
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Nuevos casos 24 horas
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -24h)
                  |> filter(fn: (r) => r["_measurement"] == "exec_brasil")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
                  |> increase()
                  |> yield(name: "increase")
        width: 2
        xPos: 4
        yPos: 1
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Chile
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "exec_chile")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
        width: 2
        xPos: 6
      - colors:
          - hex: '#ffffff'
            name: white
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Nuevos casos 24 horas
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -24h)
                  |> filter(fn: (r) => r["_measurement"] == "exec_chile")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
                  |> increase()
                  |> yield(name: "increase")
        width: 2
        xPos: 6
        yPos: 1
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Paraguay
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "exec_paraguay")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
        width: 2
        xPos: 8
      - colors:
          - hex: '#ffffff'
            name: white
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Nuevos casos 24 horas
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -24h)
                  |> filter(fn: (r) => r["_measurement"] == "exec_paraguay")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
                  |> increase()
                  |> yield(name: "increase")
        width: 2
        xPos: 8
        yPos: 1
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Uruguay
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "exec_uruguay")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
        width: 2
        xPos: 10
      - colors:
          - hex: '#ffffff'
            name: white
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Nuevos casos 24 horas
        queries:
          - query: |-
                from(bucket: "covid")
                  |> range(start: -24h)
                  |> filter(fn: (r) => r["_measurement"] == "exec_uruguay")
                  |> filter(fn: (r) => r["_field"] == "location_latest_confirmed")
                  |> increase()
                  |> yield(name: "increase")
        width: 2
        xPos: 10
        yPos: 1
    name: COVID19 América del Sur y Resto del mundo
---

apiVersion: influxdata.com/v2alpha1
kind: Telegraf
metadata:
    name: covid19-southamerica
spec:
    associations:
      - kind: Label
        name: vigorous-pike-607001
    config: |
         [[outputs.influxdb_v2]]
         ## The URLs of the InfluxDB cluster nodes.
         ##
           ## Multiple URLs can be specified for a single cluster, only ONE of the
           ## urls will be written to each interval.
           ## urls exp: http://127.0.0.1:9999
           urls = ["$INFLUX_HOST"]
         
           ## Token for authentication.
           token = "$INFLUX_TOKEN"
         
           ## Organization is the name of the organization you wish to write to; must exist.
           organization = "$INFLUX_ORG"
         
           ## Destination bucket to write into.
           bucket = "$INFLUX_BUCKET"
         
           [agent]
           interval = "3h"
         
         [[inputs.exec]]
           ## Commands array
           commands = [
             "sh argentina.sh"
           ]
         
           ## Timeout for each command to complete.
           timeout = "30s"
         
           ## measurement name suffix (for separating different commands)
           name_suffix = "_argentina"
         
           ## Data format to consume.
           ## Each data format has its own unique set of configuration options, read
           ## more about them here:
           ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
           data_format = "json"
         
         [[inputs.exec]]
           ## Commands array
           commands = [
            "sh uruguay.sh"
           ]
         
           ## Tind to complete.
           timeout = "30s"
         
           ## measurement name suffix (for separating different commands)
           name_suffix = "_uruguay"
         
           ## Data format to consume.
           ## Each data format has its own unique set of configuration options, read
           ## more about them here:
           ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
           data_format = "json"
         
         [[inputs.exec]]
           ## Commands array
           commands = [
            "sh bolivia.sh"
           ]
         
           ## Timeout for each command to complete.
           timeout = "30s"
         
           ## measurement name suffix (for separating different commands)
           name_suffix = "_bolivia"
         
           ## Data format to consume.
           ## Each data format has its own unique set of configuration options, read
           ## more about them here:
           ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
           data_format = "json"
         
         [[inputs.exec]]
           ## Commands array
           commands = [
             "sh brasil.sh"
           ]
         
           ## Timeout for each command to complete.
           timeout = "30s"
         
           ## measurement name suffix (for separating different commands)
           name_suffix = "_brasil"
         
           ## Data format to consume.
           ## Each data format has its own unique set of configuration options, read
           ## more about them here:
           ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
           data_format = "json"
         
         [[inputs.exec]]
           ## Commands array
           commands = [
            "sh chile.sh"
           ]
         
           ## Timeout for each command to complete.
           timeout = "30s"
         
           ## measurement name suffix (for separating different commands)
           name_suffix = "_chile"
         
           ## Data format to consume.
           ## Each data format has its own unique set of configuration options, read
           ## more about them here:
           ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
           data_format = "json"
         
         [[inputs.exec]]
           ## Commands array
           commands = [
            "sh paraguay.sh"
           ]
         
           ## Timeout for each command to complete.
           timeout = "30s"
         
           ## measurement name suffix (for separating different commands)
           name_suffix = "exe_paraguay"
         
           ## Data format to consume.
           ## Each data format has its own unique set of configuration options, read
           ## more about them here:
           ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
           data_format = "json"
         
         [[inputs.exec]]
           ## Commands array
           commands = [
            "sh worldwide.sh"
           ]
         
           ## Timeout for each command to complete.
           timeout = "30s"
         
           ## measurement name suffix (for separating different commands)
           name_suffix = "_worldwide"
         
           ## Data format to consume.
           ## Each data format has its own unique set of configuration options, read
           ## more about them here:
           ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
           data_format = "json"
name: Exec Inputs