#!/usr/bin/env python3

import pathlib

file_contents = '''
# This is a file generated by the scripts/generate script
---
\tproject-name: new_project
  templates:
  \t # paths are relative to this metadata file's location
  \t - template_file: example.yml
  \t - template_file: directory/example.yml
  \t # a leading slash indicates root of community-templates project:
  \t - template_file: /downsampling/dashboards.yml
  author: InfluxData
  website: www.influxdata.com
  screenshots:
  \t - img/screenshot1.png
  \t - img/screenshot2.png
  \t - /downsampling/img/dashboard.png'''.expandtabs(2)

file_contents += '\n'
file_contents = file_contents.strip()
print(file_contents)

home_dir = pathlib.Path(__file__).resolve().parent.parent
generated_filename = './metadata.yml'

print("Writing to manifest file %s\n" % (generated_filename))

manifest_file = open(generated_filename, 'w')
manifest_file.write(file_contents)
manifest_file.close()

