{
 "title": "Apex Legends",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![](https://i.imgur.com/dQ0YK2k.png)\n\n![](https://gamepedia.cursecdn.com/apexlegends_gamepedia_en/2/20/Badge_Apex_Predator.png?version=ca48fdedb4bdd43ecc4fe3daeead452e)"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Player Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "apexlegends_global",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "apexlegends_global",
     "select": [
      [
       { "params": [ "platform" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rank Tier",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "apexlegends_global",
     "select": [
      [
       { "params": [ "rank_rankScore" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Player Level",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "apexlegends_global",
     "select": [
      [
       { "params": [ "level" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Games Played",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "apexlegends_totals",
     "select": [
      [
       { "params": [ "games_played_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Kills",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "apexlegends_totals",
     "select": [
      [
       { "params": [ "kills_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Legend",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "apexlegends_realtime",
     "select": [
      [
       { "params": [ "selectedLegend" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "apexlegends_realtime",
     "select": [
      [
       { "params": [ "isOnline" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rank Score",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "apexlegends_global",
     "select": [
      [
       { "params": [ "rank_rankScore" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "BattlePass Level",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "apexlegends_global_battlepass",
     "select": [
      [
       { "params": [ "level" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kill/Death Ratio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "apexlegends_totals",
     "select": [
      [
       { "params": [ "kd_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kills as Kill Leader",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "apexlegends_totals",
     "select": [
      [
       { "params": [ "kills_as_kill_leader_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kills Per Legend",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Bangalore",
     "measurement": "apexlegends_legend_bangalore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "BloodHound",
     "measurement": "apexlegends_legend_bloodhound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Loba",
     "measurement": "apexlegends_legend_loba",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Mirage",
     "measurement": "apexlegends_legend_mirage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Octane",
     "measurement": "apexlegends_legend_octane",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Pathfinder",
     "measurement": "apexlegends_legend_pathfinder",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Wraith",
     "measurement": "apexlegends_legend_wraith",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Lifeline",
     "measurement": "apexlegends_legend_lifeline",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Caustic",
     "measurement": "apexlegends_legend_caustic",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Gibraltar",
     "measurement": "apexlegends_legend_gibraltar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Wattson",
     "measurement": "apexlegends_legend_wattson",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Crypto",
     "measurement": "apexlegends_legend_crypto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    },
    {
     "alias": "Revenant",
     "measurement": "apexlegends_legend_revenant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "kills" }
     ]
    }
   ]
  },
  {
   "title": "Games Played Per Legend",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Bangalore",
     "measurement": "apexlegends_legend_bangalore",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "BloodHound",
     "measurement": "apexlegends_legend_bloodhound",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Loba",
     "measurement": "apexlegends_legend_loba",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Mirage",
     "measurement": "apexlegends_legend_mirage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Octane",
     "measurement": "apexlegends_legend_octane",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Pathfinder",
     "measurement": "apexlegends_legend_pathfinder",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Wraith",
     "measurement": "apexlegends_legend_wraith",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Lifeline",
     "measurement": "apexlegends_legend_lifeline",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Caustic",
     "measurement": "apexlegends_legend_caustic",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Gibraltar",
     "measurement": "apexlegends_legend_gibraltar",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Wattson",
     "measurement": "apexlegends_legend_wattson",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Crypto",
     "measurement": "apexlegends_legend_crypto",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    },
    {
     "alias": "Revenant",
     "measurement": "apexlegends_legend_revenant",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "key", "operator": "=", "value": "games_played" }
     ]
    }
   ]
  }
 ]
}